### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Anewri32** [murao-kun/Debugify-reforged#5]
### Bug Description

None

### Version

1.0.0

### Mod Loader Version

43.2.0

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/NhuRsDI

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by Yourname942** [comment]
I have this same immediate crash issue:

`Exception in thread "main" java.lang.module.ResolutionException: Modules debugify and MixinExtras.beta._6 export package com.llamalad7.mixinextras to module netherdepthsupgrade

	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)

	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)

	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)

	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)

	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)

	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)

	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)`
